### ISSUE TITLE
No text+ found in the media pool

### ISSUE THREAD

**Issue by VictorHendricus** [tmoroney/auto-subs#10]
After the script finishes transcribing it says this:
![image](https://github.com/tmoroney/auto-subs/assets/88241674/a4061d15-76d5-4bc6-b2f2-360ce2345b57)
And if i go to the destination it talks about, i can see the file with subtitles.

**Comment by Gr3su** [comment]
Hey,
go watch the video tutorial by the creator ( https://youtu.be/--4vfAM9_tI ).
There he shows you that you need to create a Text+ Layer in Davinci itself. After you created it you need to add it to the Media Pool, then it should work.
