### ISSUE TITLE
Delayed for 6497th time, please give us a realistic date

### ISSUE THREAD

**Issue by GabrielM33** [tmoroney/auto-subs#108]

**Comment by Ev212** [comment]
fr

**Comment by tmoroney** [comment]
There are issues with the code signing on Mac which is causing the delay. Also I am not working on this full time, I have to balance this with my master's degree. So unfortunately I can't really give an exact date other than hopefully it will be released for Mac before end of this week, and a few days more for Windows. However, there are always issues that pop up which may delay it.

**Comment by GabrielM33** [comment]
Then instead of giving unrealistic dates, just say you don't know. Don't make people wait for nothing.

**Comment by plutowootoe** [comment]
> Then instead of giving unrealistic dates, just say you don't know. Don't make people wait for nothing.

This is an open source project by a man doing a masters degree at the same time. Download the project and work on it yourself, if it is this important.

**Comment by RonanGrennan** [comment]
> Then instead of giving unrealistic dates, just say you don't know. Don't make people wait for nothing.

it's literally a free project by 1 person that's also in college you stupid cunt

**Comment by GabrielM33** [comment]
Look at the keyboard warrior. I wasn’t trying to bash him. I appreciate his efforts and all, but I’ve been waiting weeks for this, and it keeps getting delayed. I just don’t think it’s fair to give someone a date and then never deliver on it, repeatedly.

**Comment by tmoroney** [comment]
Well it is free software, so I believe your expectations are a little high 👍

**Comment by GabrielM33** [comment]
What do you mean? Being free or not has no bearing on unfulfilled promises.

**Comment by noobzoid0** [comment]
> What do you mean? Being free or not has no bearing on unfulfilled promises.

you can always work on it yourself, it is open source 😊
either way mac version is out and windows is coming in a few days

**Comment by GabrielM33** [comment]
I gave it a try and it works like a charm. Thank you, I appreciate the effort.
