### ISSUE TITLE
Auto Sub not working after reinstall

### ISSUE THREAD

**Issue by luxentx** [tmoroney/auto-subs#115]
Hi, can anyone help?
 I accidentally updated to davinci resolve 19.1. I uninstalled it and when back to 19.0.3 After that, I found my auto-subs is not working. I tried reinstalling but I keep getting the error below:

  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Utility\auto-subs.py", line 114
    <title>auto-subs/auto-subs.py at main · tmoroney/auto-subs · GitHub</title>
                                          ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by AdyTech99** [comment]
Weird, try deleting the auto-subs.py from utility folder and re-downloading it

**Comment by luxentx** [comment]
> Weird, try deleting the auto-subs.py from utility folder and re-downloading it

Hi, I tried this a few times. Didn't work.

**Comment by luxentx** [comment]
I restored my windows 11 and reinstalled everything. Got it to work now.

**Comment by luxentx** [comment]
I restored my windows 11 and reinstalled everything. Got it to work now.
