### ISSUE TITLE
Is this not compatible with 19.1?

### ISSUE THREAD

**Issue by WesleyAldridge** [tmoroney/auto-subs#116]
When I try to use it, I get a popup message saying "You've reached a limitation with Davinci Resolve" asking me to pay $300 to use the script. Is it no longer compatible? What version(s) is it compatible with?

**Comment by AdyTech99** [comment]
It does not work with 19.1 due to Blackmagic Design paywalling certain core features. You need DaVinci 19.0.3

If you're on Mac, you can use AutoSubs v2 which fixes the issue. Windows version will be out in a few days.

**Comment by Ev212** [comment]
how do i downgrade

**Comment by tmoroney** [comment]
Uninstall resolve and download the version before 19.1
