### ISSUE TITLE
Failed to connect to Davinci Resolve via AutoSubs Link

### ISSUE THREAD

**Issue by jdn4evr** [tmoroney/auto-subs#117]
downloaded the new v2 and before it was going well it generated through but it didnt add any and popped up with this message (btw i used v1 and it worked perfectly and still does so idk if there was an update possibly done)
<img width="1680" alt="Screenshot 2024-11-22 at 3 52 26 PM" src="https://github.com/user-attachments/assets/86004844-f4a3-41e5-ad99-ea51c578e383">
<img width="1678" alt="Screenshot 2024-11-22 at 3 55 10 PM" src="https://github.com/user-attachments/assets/11039d1f-6f21-4e80-b8ed-86c822fdeeeb">

**Comment by g-i-kala** [comment]
Same here.

**Comment by jdn4evr** [comment]
its fixed now download his new update
