### ISSUE TITLE
auto-sub v2.1 issues 

### ISSUE THREAD

**Issue by 4Fortune8** [tmoroney/auto-subs#128]
Resolve V19.0.1  running autosubs 2.1 i get an error 

```
Operating System: Windows
Windows-specific code
AutoSubs server is listening on port: 55010	
...n\DaVinci Resolve\Fusion\Scripts\Utility\AutoSubs V2.lua:399: An operation was attempted on something that is not a socket.
```

when i run the v2.,

**Comment by Abdu865** [comment]
sent it upgraded to 19.1.1 Did a full clean on all my  files in C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts and  C:\Users[]AccountName]\AppData\Roaming\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts to match a fresh install and it resolved the issue.

Might be good to add this to the docs
