### ISSUE TITLE
How to install Step 2?

### ISSUE THREAD

**Issue by 75415526** [tmoroney/auto-subs#13]
Well, Step 2: Install Stable-TS ... Run this command. ...
Where should I run this command?

In PowerShell? It does not work ... (The term 'pip' is not recognized ...)
In Python?  It does not work ... (invalid syntax)
In Resolve Console? It does not work ... (invalid syntax)

**Comment by 75415526** [comment]
Well, the installer does not work.
I made complet new Windows 10 reainstal ...
![Install](https://github.com/tmoroney/auto-subs/assets/142590346/8fb78046-6964-46e2-a3f7-0892254aaa8f)

**Comment by tmoroney** [comment]
Hey, I just updated the setup process which simplifies it down to one command and no download. Hopefully, it also fixes your problem.
