### ISSUE TITLE
Error during audio processing: Timestamps are not in ascending order.

### ISSUE THREAD

**Issue by SharjeelRashid** [tmoroney/auto-subs#137]
I dont know why im getting this error now. I have used the Auto-subs before for other videos and everything went good. Difference is just that now the audio content is much more than before. Im even using the Larger Whisper. Would be helpful if anybodz else also had the same issue and how to resolve it. Im pretty new to Davinci Resolve and editing videos in general.
Thanks!

**Comment by Marys101** [comment]
Did you get this resolved? I am having the same issue, just downloaded the latest version.
