### ISSUE TITLE
Light Version also does not work

### ISSUE THREAD

**Issue by 75415526** [tmoroney/auto-subs#14]
First at all, in the setup of lite version there is a mistake.
"Skip step 1 of the installation guide" is not true.
You have to install Python, which is part of step 1.

After installation i load [auto-subs-light.py] into the Resolve Studio (18.6), i load the srt file ... but nothing happends.

Sorry bro ... nothing works here.

**Comment by tmoroney** [comment]
I just tested the light version and it is working correctly. You might want to check the updated documentation and try again.
