### ISSUE TITLE
Easier way to set up on macOS

### ISSUE THREAD

**Issue by loaykhalifa** [tmoroney/auto-subs#15]
- step by step Video to setup on macos 
- Simple or more clear steps on point to set up

(https://github.com/tmoroney/auto-subs/assets/102491821/bc6030a9-5a0d-4277-a7cf-edeac71161fa)

**Comment by tmoroney** [comment]
I just pushed an update that adds utf-8 encoding to support unicode characters. Your issue should be fixed now.

I also updated the docs to make installation clearer on Mac. However, I haven't tested it because I don't have a Mac yet. I am getting one from my work soon, so I'll test it out then.

**Comment by tmoroney** [comment]
Did you install FFMPEG?
`brew install ffmpeg`

**Comment by KaMilleT** [comment]
I get the same error. FFMPEG is installed via brew and I can call it in a mac terminal:

```
ffmpeg -version
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
```

**Comment by tmoroney** [comment]
Hey, I just updated the Resolve script to automatically set the environment variables for FFMPEG and Homebrew on MacOS. This should fix the issue for you.

**Comment by HeyRaphi** [comment]
The error now is now gone, thank you, but now I have another problem, which I think is a whole other topic.
