### ISSUE TITLE
Text+ Elements are placed 1 hour after they are supposed to

### ISSUE THREAD

**Issue by HeyRaphi** [tmoroney/auto-subs#16]
Auto-Subs v1.8
Davinci Resolve 18.6
MacOS Sonoma 14.2.1

When I place In- and Out-Points and start the process with "Generate Subtitles" everything is fine until the script places the Text+ elements. They are placed not exactly one hour behind my In- and Out-Points. I assume this is due to the fact that Davinci starts with "already 1 hour on the clock". The timeline starts at 1:00:00:00 and this causes confusion.

Example:

srt file is
01:15:38,670 --> 01:15:38,930 

![image](https://github.com/tmoroney/auto-subs/assets/28729379/f6511b83-afe4-43df-bedf-188c3b0a7c2b)

text+ ist placed on
02:15:34:04

![image](https://github.com/tmoroney/auto-subs/assets/28729379/363338e1-695a-4e71-9b44-33c93e6743bc)

subtitles overview in the auto-subs window:
03:15:45:26

![image](https://github.com/tmoroney/auto-subs/assets/28729379/a70de66a-0053-4708-b344-ed53d0500223)

Something is very off regarding the timecodes

In addition: is there an option in the current version to just create the SRT file and skip the placing of the Text+ element like it was possible in the old version?

Thank you very much. I can only imagine how big of a pain in the butt this was to code.

**Comment by HeyRaphi** [comment]
At the moment I am working with an altered v1.5 where I added the MacOS path check from 1.8 and there I only use the "Transcribe to subtitles file" functionwhich works perfectly for my needs.

So no need to hurry.

**Comment by tmoroney** [comment]
Hey, I updated the script to fix this issue that was caused by the timeline starting timecode not being 00:00:00. So if you download the latest version of auto-subs.py it should be fixed :)

**Comment by HeyRaphi** [comment]
Works as expected. Thank you very much.
