### ISSUE TITLE
DecodingOptions.__init__() got an unexpected keyword argument 'regroup'

### ISSUE THREAD

**Issue by philexh** [tmoroney/auto-subs#22]
I keep running into issues with the script not running, 

Audio Rendering Complete!
Transcribing Audio...
DecodingOptions.__init__() got an unexpected keyword argument 'regroup'

After removing the "regroup" and "only_voice_freq"(which also didn't let my code go through), it still gives out an error for:

'dict' object has no attribute 'split_by_punctuation'
'dict' object has no attribute 'merge_by_gap'
'dict' object has no attribute 'split_by_length'

Removing those steps, I just got stuck on this:

'dict' object has no attribute 'to_srt_vtt'

Any help on what's up is appreciated!

**Comment by tormyvancool** [comment]
> I keep running into issues with the script not running,
> 
> Audio Rendering Complete! Transcribing Audio... DecodingOptions.**init**() got an unexpected keyword argument 'regroup'
> 
> After removing the "regroup" and "only_voice_freq"(which also didn't let my code go through), it still gives out an error for:
> 
> 'dict' object has no attribute 'split_by_punctuation' 'dict' object has no attribute 'merge_by_gap' 'dict' object has no attribute 'split_by_length'
> 
> Removing those steps, I just got stuck on this:
> 
> 'dict' object has no attribute 'to_srt_vtt'
> 
> Any help on what's up is appreciated!

Got the same error after I was able to make it running. here the link https://github.com/tmoroney/auto-subs/issues/19

**Comment by philexh** [comment]
Yeah, got it fixed by reinstalling brew and python!

**Comment by Miacrocosm** [comment]
Fixed it. 
Replace, 
result = model.transcribe(location, fp16=False, regroup=True, only_voice_freq=True) # transcribe audio file
with, 
result = model.transcribe(location, fp16=False, only_voice_freq=True) # transcribe audio file
