### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by MRgro0** [tmoroney/auto-subs#37]
I have seen that others have had a similar problem where subtitles fail to transcribe to the timeline due to the text template selection not having options as described in #31 A possible solution is also mentioned in #36 however, after testing with the changes made, the bug remained with the same error result

 Using model -> [ small ]
MarkIn: 108000
Rendering Audio for Transcription...
Progress:  100 %
Audio Rendering Complete!
Transcribing Audio...

Transcribe:   0%|          | 0/4.25 [00:00<?, ?sec/s]
                                                     
Detected language: spanish

Transcribe:   0%|          | 0/4.25 [00:02<?, ?sec/s]
Transcribe: 100%|##########| 4.25/4.25 [00:10<00:00,  2.57s/sec]
Transcribe: 100%|##########| 4.25/4.25 [00:10<00:00,  2.57s/sec]
Saved: C:\Users\MRgro_0\AppData\Roaming\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility\audio.srt
Transcription Complete!
Subtitles saved to -> [ C:\Users\MRgro_0\AppData\Roaming\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility\audio.srt ]
Adjusting timestamps by 0:00:00
Found 4 subtitles in SRT file
list index out of range

I followed the instructions specified for automatic setup

**Comment by MRgro0** [comment]
That modification brought new problems and the script stopped running, I didn't save the error message in the console but restore Davinci Resolve from factory this time without changing the language to spanish and that solved all the problems even without adjustments in the script, so if someone else has this same problem it will probably be solved by simply changing the language of the program.

**Comment by Thomsd2** [comment]
Sorry to reopen this issue, but I couldn't find the Text+ in the menu, despite having them (tried to have 2) added to the Media Pool. I installed the software in English, and here is what the Python change gave me:
"Video + Audio
Timeline
Fusion Title
Fusion Title"

I am running Davinci Resolve Version 19.0B Build 20 and Python 3.12.3

**Comment by samhitech** [comment]
Just adjust the script according to the version in my fork, for now, it should work fine.
Let me know if it does not work.
```python

CLIP_TYPES_LOCALE = [
   'Título – Fusion', # spanish
   "Título Fusion", # portuguese
   "Generator", # en-us?
   "Fusion Title", # English
   "Titre Fusion", # French
   "Титры на стр. Fusion", # Russian
   "Fusion Titel", # German
   "Titolo Fusion", # Italian
   "Fusionタイトル", # Japanese
   "Fusion标题", # Chinese
   "퓨전 타이틀", # Korean
   "Tiêu đề Fusion", # Vietnamese
   "Fusion Titles", # Thai
]

def recursiveSearch(folder):
   items = folder.GetClipList()
   for item in items:
      itemType = item.GetClipProperty()["Type"]
      if itemType in CLIP_TYPES_LOCALE:
         itemName = item.GetName()
         clipName = item.GetClipProperty()['Clip Name']
         itm['Template'].AddItem(clipName)
         if re.search('text|Text|title|Title|subtitle|Subtitle', itemName) or re.search('text|Text|title|Title|subtitle|Subtitle', clipName):
            itm['Template'].CurrentIndex = len(mediaPoolItemsList) - 1 # set default template to Text+
         mediaPoolItemsList.append(item)
   subfolders = folder.GetSubFolderList()
   for subfolder in subfolders:
      recursiveSearch(subfolder)
   return

```

**Comment by Thomsd2** [comment]
Yup I saw your pull request shortly after posting my comment, and it works like a charm 😄
