### ISSUE TITLE
cant load subtitles 

### ISSUE THREAD

**Issue by loaykhalifa** [tmoroney/auto-subs#4]
![Screen Shot 2023-06-11 at 5 03 56 PM](https://github.com/tmoroney/auto-subs/assets/102491821/c557e0f3-26ec-402e-9b5e-736718f01db7)

**Comment by tmoroney** [comment]
It appears that you have an odd character at position 32 in your audio.srt file that it can't read. I believe 0xd9 is the character Ù. Other than that I don't know what it could be.
