### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mrharryhd** [tmoroney/auto-subs#44]
![image](https://github.com/tmoroney/auto-subs/assets/148923299/6e72152e-4534-45f1-ad44-f2fa044be0bf)

**Comment by fucskonorbi** [comment]
In powershell you could try to do 
`python -m pip install stable-ts`
Make sure your python version is the same as in Davinci Resolve. After installation you might have to restart Davinci.

(To check in Powershell you can do `python -c "import sys; print(sys.version)"`, then to check in Davinci you can click on the Py3 panel in the console and type in `import sys` then `print(sys.version)`.)

**Comment by mrharryhd** [comment]
nvm i fixed 6hrs later after i opened this post 

i added 

"import sys
     sys.path.append('C:\\Users\\your_username\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages')  # Replace 'your_username' with your actual username
     import stable_whisper

     import time
     import re
     from datetime import datetime, timedelta
     import os
     import platform"

**Comment by mrharryhd** [comment]
nvm i fixed 6hrs later after i opened this post

i added

"import sys
sys.path.append('C:\Users\your_username\AppData\Local\Programs\Python\Python312\Lib\site-packages') # Replace 'your_username' with your actual username
import stable_whisper

 import time
 import re
 from datetime import datetime, timedelta
 import os
 import platform"
