### ISSUE TITLE
Biggest Issue

### ISSUE THREAD

**Issue by Vision-Live** [tmoroney/auto-subs#5]
Transcribing Audio...
Failed to load audio: ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
C:\Users\Suoxe\AppData\Roaming\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility\audio.unknown: No such file or directory

I got it to transcribe once. But then the rest failed. Even with the new pushed version, the Format always changes to wave but MP3 codec stays the same.

**Comment by Vision-Live** [comment]
I managed to initiate transcription by downloading the raw python file and replacing the zipped one. I also in finder showed hidden items and accessed the ffmpeg folder through the chocolaty directory. 

After recreating the keyframes in the text+ object, and re-enabling the text+ option. It showed up in the media pool. Which leads me to the next problem.

Saved: C:\Users\Suoxe\AppData\Roaming\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility\audio.srt
Transcription Complete!
Subtitles saved to -> [ C:\Users\Suoxe\AppData\Roaming\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility\audio.srt ]
Using custom subtitles from -> [ C:\Users\Suoxe\AppData\Roaming\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility\audio.srt ]
Found Text+ in Media Pool!
Adding template subtitles...
Updating text content...

The adding function is not completed and the text does not get updated. However If I have a text object in the timeline it gets updated.

**Comment by tmoroney** [comment]
Are your In and out points set correctly on the timeline i.e. to the area you are trying to subtitle?

**Comment by Vision-Live** [comment]
> Are your In and out points set correctly on the timeline i.e. to the area you are trying to subtitle?

I place the in and out anywhere on the timeline, and there is no executiion. It says it updates but doesn't actually do so. 

Same issue with Davinci resolve 18 and 18.5 on windows 11. Not tried it on Windows 10.

**Comment by tmoroney** [comment]
It seems there is a bug here because a few people are having this issue. I am working on it now with one of them because I cannot replicate the issue.

**Comment by tmoroney** [comment]
> > Are your In and out points set correctly on the timeline i.e. to the area you are trying to subtitle?
> 
> I place the in and out anywhere on the timeline, and there is no executiion. It says it updates but doesn't actually do so. 
> 
> Same issue with Davinci resolve 18 and 18.5 on windows 11. Not tried it on Windows 10. 

Just pushed an update that hopefully fixes your issue.
