### ISSUE TITLE
Error when transcribing audio

### ISSUE THREAD

**Issue by 404CrypticNotFound** [tmoroney/auto-subs#6]
```
Using model -> [ medium.en ]
Rendering Audio for Transcription...
Progress:  0 %
Progress:  100 %
Audio Rendering Complete!
Transcribing Audio...
[WinError 193] %1 is not a valid Win32 application
```

Not sure where this would be caused because the lack of a traceback in the console.

**Comment by 404CrypticNotFound** [comment]
Looks like the build of ffmpeg that was installed was messed up, after manually reinstalling ffmpeg, the issue has stopped.

**Comment by tmoroney** [comment]
Oh, that's an issue I've never seen before. Was it the Powershell script that installed the bad build of FFmpeg?

**Comment by 404CrypticNotFound** [comment]
I'm not 100% sure
