### ISSUE TITLE
Script does not see start and end points

### ISSUE THREAD

**Issue by Anon1m4ik** [tmoroney/auto-subs#7]
![Resolve_CSr3qTFY3I](https://github.com/tmoroney/auto-subs/assets/71006333/f4e05738-9ef5-4fcf-8b7b-9d8fa9b84b32)
I don't know why, but it doesn't want to recognize start and end points. Davinci version 18.5

**Comment by tmoroney** [comment]
You need to place a blue marker at the beginning and end of the segment to subtitle.
![image](https://github.com/tmoroney/auto-subs/assets/72154813/80f18896-27be-4998-9698-1170acbb4583)

**Comment by Anon1m4ik** [comment]
Thanks! I'll try.
