### ISSUE TITLE
Plugin Window not opening when clicking auto-subs (Davinci Resolve 19)

### ISSUE THREAD

**Issue by CreativeNick** [tmoroney/auto-subs#87]
I seemed to successfully install the plugin using the automatic Windows method, but nothing happens when I click on Workspace --> Scripts --> auto-subs. The window does not open. The python file `auto-subs.py` is also in the proper scripts folder, so I'm not really sure why the window is not opening.

I'm using Davinci Resolve 19 on Windows 11.

Below is my terminal output:
```
PS C:\WINDOWS\system32> Invoke-Expression (Invoke-WebRequest -Uri "https://raw.githubusercontent.com/tmoroney/auto-subs/main/update-script.ps1").Content
Downloading latest version of auto-subs.py...
auto-subs.py downloaded successfully.
Placed in directory - C:\ProgramData\Blackmagic Design\DaVinci Resolve\Fusion\Scripts\Utility
You can now access the script in DaVinci Resolve from Workspace -> Scripts in the top menu.
```

**Comment by CreativeNick** [comment]
Update: Nevermind! There was a slight issue with my install but it works now!

**Comment by NoelDavies** [comment]
How did you fix this @CreativeNick
