### ISSUE TITLE
Subtitle Elements Added as Blank in Video Track Despite SRT Generation

### ISSUE THREAD

**Issue by SadmanSyfe** [tmoroney/auto-subs#91]
Hello,
The script is generating the .srt file, and the text elements are being added as well. However, the issue is that the text elements are empty; they're being added as blank elements on the video track without any text in them. I am using the latest resolve 19.

![Screenshot (204)](https://github.com/user-attachments/assets/c18a8057-51ea-46b5-a3e4-7983a6ed3636)

**Comment by Azyrod** [comment]
I have the same issue. I would love this resolved !

**Comment by SadmanSyfe** [comment]
> I have the same issue. I would love this resolved !

Use **Text+** element. Solved it for me.
